language: ruby
rvm:
- 2.4
- 2.5
dist: trusty
sudo: false
gemfile: ".travis.gemfile"
env:
  global:
  - CONCEPTQL_DATA_MODEL=omopv4_plus
  - secure: krTfSi0Itzy6NbTg3Fe/H/uyI5mjG6tYjE6G5zSmkl4ftmiDZ8ziI8YEXl5tnOlQtCPJxHzCLFlzfxFle11g+8at8WA7Fc3zwC+LEIDGV7HLG2dev4K18vM7sAtbvbFseprJGQZb1jWf7rez6ie3cp0K4SeLzRl5HWMyCj/HG3A=
  matrix:
  - CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=scratch SEQUELIZER_URI="postgres://localhost/synpuf_250_20160815?username=postgres" USING_POSTRESQL=true
  - CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="postgres://localhost/synpuf_250_20160815?username=postgres" USING_POSTRESQL=true
  - CONCEPTQL_FORCE_TEMP_TABLES=true DOCKER_SCRATCH_DATABASE=scratch SEQUELIZER_URI="impala://nonworker1.hadoop.jsaw.io/synpuf250" USING_IMPALA=true
  - CONCEPTQL_FORCE_TEMP_TABLES=false SEQUELIZER_URI="impala://nonworker1.hadoop.jsaw.io/synpuf250" USING_IMPALA=true
addons:
  postgresql: '9.6'
  apt:
    packages:
    - python-pip
services:
- postgresql
before_install:
- bash .travis.postgres.sh
- bash .travis.impala.sh
before_script:
- bundle exec rake diagnostics
script: travis_wait 40 bundle exec ruby test/all.rb
notifications:
  slack:
    secure: YrvvLrIOgRIzqb01GbektA0YZXCieghuhaU3O4vBW/otrz26twb/0zeB/HHqKS3P2re0R127wGw6nAUAG9ieEHPYMKcpZZWzvnPrqQ/5ASbIZWX85fps0svFEeQTqRjK8TdHC/0ZJoy3P7i6wgBoWcs434aSR4K6KgisdWJATk0=

jobs:
  include:
    - stage: Ping Jigsaw
      before_install: gem install tping
      before_script: skip
      script:
        - tping $TRAVIS_PRO_TOKEN outcomesinsights jigsaw-diagram-editor pro
        - tping $TRAVIS_PRO_TOKEN outcomesinsights t_shank pro

